---
title: "PCA"
author: "Antoine Lachance-Perreault"
date: '2022-04-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(data.table)
library(haven)
library(tidyverse)
library(tidymodels)
#library(tidylayers)
library(tidytext)
#library(segter)
library(ggspatial)
library(sf)
#library(touski)
library(ggthemr)
ggthemr("flat")
theme_set(theme_bw() + theme(legend.position = "bottom"))
rosm::set_default_cachedir("/home/actuariat/data/cache/rosm/")
```


```{r read_data}

geo_demo_dat <- read_csv(file = "../data/Donnees_GeoDemo_QC_NB_2016.csv",
                         col_types = cols(ADIDU = col_character(), 
                                          PRIDU = col_character(),
                                          SDRIDU = col_character()), 
                         locale = locale(encoding = "latin1")) %>% 
  janitor::clean_names() %>% 
  filter(pridu == "24")

dir.create("temp")
unzip("../data/ad_boundaries.zip", exdir = "temp")
unzip("../data/ad_aggrege.zip", exdir = "temp")
unzip("../data/sdr_boundaries.zip", exdir = "temp")
unzip("../data/lakes_and_rivers.zip", exdir = "temp")
unzip("../data/coastal_waters.zip", exdir = "temp")
unzip("../data/rivers.zip", exdir = "temp")

ad_layer <- read_sf("temp/lda_000b16a_e.shp") %>% 
  janitor::clean_names() %>% 
  filter(pruid == "24")

adag_layer <- read_sf("temp/lada000b16a_e.shp") %>% 
  janitor::clean_names() %>% 
  filter(pruid == "24")


sdr_layer <- read_sf("temp/lcsd000b16a_e.shp") %>% 
  janitor::clean_names() %>% 
  filter(pruid == "24") %>% 
  rename(name = csdname)


water_layer <- bind_rows(
  #lakes and rivers
  read_sf("temp/lhy_000d16a_e.shp") %>% filter(PRUID == "24") %>% select(geometry),
  #rivers
  read_sf("temp/lhy_000d16a_e.shp") %>% filter(PRUID == "24") %>% select(geometry),
  #coastal waters:
  read_sf("temp/lhy_000h16a_e.shp") %>% filter(PRUID == "24") %>% select(geometry)
)


unlink("temp", recursive=TRUE)
```

```{r}
rec <- geo_demo_dat %>% 
  mutate(
    prop_immigrants = nb_immigrants / (nb_immigrants + nb_non_immigrants),
    prop_bacc = nb_bacc / population_2016
  ) %>% 
  mutate(
    across(
      .cols = c(densite_pop_km2, taille_moy_menage_priv, revenu_total_median_2015, revenu_total_median_menage, frais_logement_mensuel_moy, taux_chomage),
      .fns = ~ifelse(.x == 0, NA, .x)
    )
  ) %>% 
  recipe(~ adidu +densite_pop_km2 + revenu_total_median_2015 + 
           revenu_total_median_menage + prop_immigrants + frais_logement_mensuel_moy + 
           valeur_moy_resi + age_moy_residences + prop_bacc) %>% 
  update_role("adidu", new_role = "key") %>% 
  step_normalize(all_numeric_predictors()) %>% 
  step_impute_knn(all_numeric_predictors()) %>% 
  step_pca(all_numeric(), 
           keep_original_cols = T,
           num_comp = 999)


prep_rec <- prep(rec)
baked_rec <- prep_rec %>% bake(new_data = NULL)


pca_res <- tidy(prep_rec, 3)

pca_res %>%
  filter(component %in% paste0("PC", 1:4)) %>%
  group_by(component) %>%
  top_n(10, abs(value)) %>%
  ungroup() %>%
  mutate(terms = reorder_within(terms, abs(value), component),
         value_flip = case_when(
           component %in% c("PC2") ~ -value,
           TRUE ~ value
         )) %>%
  ggplot(aes(value_flip, terms, fill = value_flip > 0)) +
  geom_col() +
  facet_wrap(~component, scales = "free_y") +
  scale_y_reordered() +
  labs(
    x = "Contribution",
    y = NULL, fill = "Positif?"
  ) + 
  theme(legend.position = "none")

```


```{r}


(prep_rec$steps[[3]]$res$sdev^2 / sum(prep_rec$steps[[3]]$res$sdev^2)) %>% cumsum()

prep_rec$steps[[3]]$res %>% summary()

pct_var <- tibble(
  PC = paste0(rep("PC", length(prep_rec$steps[[3]]$res$sdev)), 1:length(prep_rec$steps[[3]]$res$sdev)),
  pct_var = prep_rec$steps[[3]]$res$sdev^2 / sum(prep_rec$steps[[3]]$res$sdev^2)
) %>% 
  ggplot(aes(x = PC, y = pct_var)) +
  geom_col() +
  # coord_flip() +
  labs(x = "", y = "% de la variance")

pct_var_cum <- tibble(
  PC = c("", paste0(rep("PC", length(prep_rec$steps[[3]]$res$sdev)), 1:length(prep_rec$steps[[3]]$res$sdev))),
  pct_var = c(0, cumsum(prep_rec$steps[[3]]$res$sdev^2 / sum(prep_rec$steps[[3]]$res$sdev^2)))
) %>% 
  ggplot(aes(x = PC, y = pct_var, group = 1)) +
  geom_point() +
  geom_line() +
  ylim(0, 1) +
  labs(x = "", y = "% cumulatif de la variance")


cowplot::plot_grid(pct_var, pct_var_cum)
```






```{r}
baked_rec %>% 
  ggplot(aes(x = PC1)) +
  stat_ecdf()

baked_rec %>% 
  ggplot(aes(x = PC1)) +
  stat_density()

quantile(baked_rec$PC1, c(0.025, 0.975))
```




```{r}
ad <- ad_layer %>% 
  inner_join(baked_rec, by = c("dauid" = "adidu")) %>% 
  mutate(
    PC2 = -PC2,
    pc1_rescaled = PC1 %>% pmin(quantile(PC1, c(0.975))) %>% pmax(quantile(PC1, c(0.025))),
    pc2_rescaled = PC2 %>% pmin(quantile(PC2, c(0.975))) %>% pmax(quantile(PC2, c(0.025))),
    pc1_rescaled = (pc1_rescaled - min(pc1_rescaled)) / (max(pc1_rescaled) - min(pc1_rescaled)) * 100,
    pc2_rescaled = (pc2_rescaled - min(pc2_rescaled)) / (max(pc2_rescaled) - min(pc2_rescaled)) * 100
  )


```


```{r, out.width=500}
# TODO: Utiliser gghighlight pour zoomer sur genre sillery

get_bbox <- function(sdr){
  sdr_layer %>% 
  filter(name %in% c(sdr)) %>% 
  select(geometry) %>% 
  pull() %>% 
  st_bbox()
}

qc_complet_pc1 <- 
  #as_reprojected_sf(sf_column_name = "shape", crs = 3857L) %>% 
  ggplot() +
  # annotation_map_tile(
  #   zoomin = 1L,
  #   type = "cartolight",
  # ) +
  geom_sf(aes(geometry = geometry, fill = pc1_rescaled), data = ad, alpha = 0.5) +
  geom_sf(aes(geometry = geometry), data = water_layer, fill = "#00b3ff") +
  scale_fill_gradient(low = "#90EE90", high = "#FF7F7F") +
  labs(fill = "PC1", x = "", y = "")

#qc à montréal
mtl_qc_bbox <- get_bbox(c("Montréal", "Québec"))
qc_complet_pc1 +
  coord_sf(xlim = c(mtl_qc_bbox[c("xmin", "xmax")]), ylim = c(mtl_qc_bbox[c("ymin", "ymax")])) +
  labs(title = "Région urbaine de Québec à Montréal")

#Montréal
mtl_bbox <- get_bbox("Montréal")
qc_complet_pc1 + 
  coord_sf(xlim = c(mtl_bbox[c("xmin", "xmax")]), ylim = c(mtl_bbox[c("ymin", "ymax")])) +
  labs(title = "Région de Montréal")


qc_bbox <- get_bbox("Québec")
qc_complet_pc1 + 
  coord_sf(xlim = c(qc_bbox[c("xmin", "xmax")]), ylim = c(qc_bbox[c("ymin", "ymax")])) +
  labs(title = "Région de Québec")



```


```{r, out.width=500}
qc_complet_pc2 <- 
  #as_reprojected_sf(sf_column_name = "shape", crs = 3857L) %>% 
  ggplot() +
  # annotation_map_tile(
  #   zoomin = 1L,
  #   type = "cartolight",
  # ) +
  geom_sf(aes(geometry = geometry, fill = pc2_rescaled), data = ad, alpha = 0.5) +
  geom_sf(aes(geometry = geometry), data = water_layer, fill = "#00b3ff") +
  scale_fill_gradient(low = "#90EE90", high = "#FF7F7F") +
  labs(fill = "PC2", x = "", y = "")

#qc à montréal
qc_complet_pc2 +
  coord_sf(xlim = c(mtl_qc_bbox[c("xmin", "xmax")]), ylim = c(mtl_qc_bbox[c("ymin", "ymax")])) +
  labs(title = "Région urbaine de Québec à Montréal")

#Montréal
qc_complet_pc2 + 
  coord_sf(xlim = c(mtl_bbox[c("xmin", "xmax")]), ylim = c(mtl_bbox[c("ymin", "ymax")])) +
  labs(title = "Région de Montréal")


qc_complet_pc2 + 
  coord_sf(xlim = c(qc_bbox[c("xmin", "xmax")]), ylim = c(qc_bbox[c("ymin", "ymax")])) +
  labs(title = "Région de Québec")

```

```{r}
library(ggridges)


ad %>% 
  left_join(as_tibble(sdr_layer) %>% select(csduid, sdr_name = name), by = c("csduid")) %>% 
  mutate(sdr_name = case_when(sdr_name %in% c("Québec", "Montréal") ~ sdr_name,
                              TRUE ~ "Autre")) %>% 
  ggplot(aes(x = pc1_rescaled, y = sdr_name, fill = sdr_name, color = sdr_name)) +
  geom_density_ridges(alpha = 0.7) +
  theme_minimal() +
  labs(
    title = "PC1: Affluence",
    y = ""
  ) +
  theme(legend.position = "None")

ad %>% 
  left_join(as_tibble(sdr_layer) %>% select(csduid, sdr_name = name), by = c("csduid")) %>% 
  mutate(sdr_name = case_when(sdr_name %in% c("Québec", "Montréal") ~ sdr_name,
                              TRUE ~ "Autre")) %>% 
  ggplot(aes(x = pc2_rescaled, y = sdr_name, fill = sdr_name, color = sdr_name)) +
  geom_density_ridges(alpha = 0.7) +
  theme_minimal() +
  labs(
    title = "PC2: Urbanisme",
    y = ""
  ) +
  theme(legend.position = "None")
```


```{r}
library(ggalt)

ad %>% 
  left_join(as_tibble(sdr_layer) %>% select(csduid, sdr_name = name), by = c("csduid")) %>% 
  mutate(sdr_name = case_when(sdr_name %in% c("Québec", "Montréal") ~ sdr_name,
                              TRUE ~ "Autre")) %>% 
  ggplot(aes(x = PC1, y = PC2, color = sdr_name)) +
  geom_point(alpha = 0.05) +
  stat_ellipse(level = 0.98) +
  scale_x_continuous(limits = c(-5, 5)) +
  scale_y_continuous(limits = c(-5, 5))
```

